name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - run: python -m pip install pipenv
      - run: python -m pipenv install --dev
      - run: python -m pipenv run test
